feat(flake): generate standalone configuration checks and documentation
Generate 'standalone' Home Manager configuration checks and their
corresponding documentation directly from the internal module options.

Every internal boolean module option generates two Home Manager
configuration checks, where the option itself and potentially necessary
parent options are set to the same value, while importing their
necessary dependencies. The 'checks.<SYSTEM>.standalone-<OPTION>-false'
and 'checks.<SYSTEM>.standalone-<OPTION>-true' configurations set the
concerned options to 'false' and 'true' respectively.

Simplify the '<SYSTEM>-<ACCESSIBILITY>-<SCOPE>-<NAME>' Home Manager
configuration naming convention to '<SYSTEM>-<ACCESSIBILITY>-<NAME>' by
removing 'standalone' ('<SCOPE>') configurations and renaming
'integrated' ('<SCOPE>') configurations to
'<SYSTEM>-<ACCESSIBILITY>-<NAME>'.

BREAKING CHANGE: The
'homeConfigurations.<SYSTEM>-<ACCESSIBILITY>-standalone-<NAME>.activationPackage'
Home Manager activation packages have been removed, and the
'homeConfigurations.<SYSTEM>-<ACCESSIBILITY>-integrated-<NAME>.activationPackage'
Home Manager activation packages have been renamed to
'homeConfigurations.<SYSTEM>-<ACCESSIBILITY>-<NAME>.activationPackage'.

Import From Derivation (IFD) is required to evaluate the 'checks' output
due to extracting the internal boolean module options from a dummy Home
Manager configuration. Consequently, commands like 'nix flake show'
require the '--allow-import-from-derivation' flag.

The inability to disable the Stylix module [1] causes the following
error upon running 'nix flake show --allow-import-from-derivation':

       error: a '<EXTERNAL_SYSTEM>' with features {<EXTERNAL_FEATURES>}
       is required to build '<DERIVATION>', but I am a '<HOST_SYSTEM>'
       with features {<HOST_FEATURES>}'

[1]: https://github.com/danth/stylix/issues/216